---
driver:
  name: proxy
  port: 5985
  reset_command: "exit 0"
  username: 'ChefPowerShell'
  password: 'P2ssw0rd!'

transport:
  name: winrm
  username: 'ChefPowerShell'
  password: 'P2ssw0rd!'

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 35
  client_rb:
    exit_status: :enabled

verifier:
  name: pester

platforms:
  - name: windows-server-2012r2
    driver:
      host: #YOUR NODE IP HERE

suites:
  - name: user
    run_list:
      - recipe[dsc_workshop::user]
    attributes:
  - name: website
    run_list:
      - recipe[dsc_workshop::website]
    attributes:
