source 'https://rubygems.org'

gem 'berkshelf', '~> 4.3'
gem 'chefspec', '~> 4.6'
gem 'cookstyle'
gem 'foodcritic', '~> 6.2'
gem 'kitchen-pester'
gem 'rake'
gem 'stove'
gem 'test-kitchen', '~> 1.9'
gem 'tomlrb'
gem 'kitchen-pester'
gem 'winrm-fs', '~> 0.4.2'
gem 'rb-readline'
gem 'pry-stack_explorer'
gem 'pry-byebug'
